<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>Projet Distorsion</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li>
                        <a href="index.php?route=chat">Chat</a>
                    </li>
                    <li>
                        <a href="index.php?route=about">A propos</a>
                    </li>
                
                    
                </ul>
            </nav>
        </header>
        
    </body>
</html>